[project]
name = "python-speedtest"
version = "0.2.0"
description = "Simple script to assess cpu or gpu-performance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "xgboost>=3.0.5",
]
